[build]
builder = "DOCKERFILE"
dockerfilePath = "surrealdb/Dockerfile"
watchPatterns = ["surrealdb/**"]

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
RAILWAY_DOCKERFILE_PATH = "surrealdb/Dockerfile"
